services:
  remote-touchpad:
    image: ghcr.io/mehmetercindogan/remote-services-4lan/remote-touchpad-non-auth:v1.0
    container_name: remote-touchpad
    profiles: ["manual"]
    privileged: true
    devices:
      - "/dev/uinput:/dev/uinput"
    networks:
      - nginx_net
    command: ["remote-touchpad", "-bind", "0.0.0.0:8080", "-mouse-move-speed", "2.5"]
