resolver 127.0.0.11 valid=30s;

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

upstream weylus_web {
    server host.docker.internal:1701;
}

upstream weylus_ws {
    server host.docker.internal:9001;
}

map $http_upgrade $weylus_hedef {
    default http://weylus_web;
    ~*websocket http://weylus_ws;
}

# ==============================================

auth_basic "Acess Authentication";
auth_basic_user_file /etc/nginx/.htpasswd;

server {
    listen 80;
    server_name _;
    
    auth_basic off;

    return 301 https://$host$request_uri;
}

# --- PORT 443: System Panel ---
server {
    listen 443 ssl;
    server_name _;
    ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        root /usr/share/nginx/mainPage;
        index index.html;
    }

    location /api/ {
        set $flask_target http://flask-controller:8080;
        proxy_pass $flask_target;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}

# --- PORT 9444: PDF Tools ---
server {
    listen 9444 ssl;
    server_name _;
    ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;

    location / {        
	    set $pdf_target http://pdf-processor:8080;
        proxy_pass $pdf_target;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        client_max_body_size 100M;
    }
}

# --- PORT 9445: WEYLUS ---
server {
    listen 9445 ssl;
    server_name _;
    ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass $weylus_hedef;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $http_host;

        proxy_set_header Accept-Encoding "";
        
        sub_filter '9001' '9445';
        sub_filter_once off;
        sub_filter_types application/javascript text/html;
        
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}

# --- PORT 9446: REMOTE TOUCHPAD ---
server {
    listen 9446 ssl;
    server_name _;
    ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;
    
    location / {
        set $touch_target http://remote-touchpad:8080;
        proxy_pass $touch_target;
        
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /ws {
        set $touch_ws http://remote-touchpad:8080/ws;
        proxy_pass $touch_ws;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        proxy_set_header Host $http_host;
        proxy_set_header Origin $http_origin;
        
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Port $server_port;
        
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}
